import { StudentUser, EarnedBadge } from '../types';

export const INITIAL_BADGES: Record<string, Omit<EarnedBadge, 'id' | 'studentId' | 'awardedAt'>> = {
  first_session: {
    badgeKey: 'first_session',
    name: 'First Exchange',
    description: 'Completed your first peer learning session on campus.',
    icon: 'Sparkles',
    criteria: 'Complete at least 1 verified peer learning session as teacher or learner.',
  },
  top_mentor: {
    badgeKey: 'top_mentor',
    name: 'Top Mentor',
    description: 'Earned stellar reviews by mentoring multiple campus peers.',
    icon: 'Award',
    criteria: 'Teach 2+ sessions with an average rating of 4.5 stars or above.',
  },
  multi_skill: {
    badgeKey: 'multi_skill',
    name: 'Skill Pioneer',
    description: 'Versatile knowledge sharer offering 3 or more distinct skills.',
    icon: 'Zap',
    criteria: 'List and successfully teach across 3 or more distinct skill domains.',
  },
  quick_learner: {
    badgeKey: 'quick_learner',
    name: 'Knowledge Seeker',
    description: 'Actively participating and learning new skills from peers.',
    icon: 'BookOpen',
    criteria: 'Complete at least 2 sessions as an eager learner.',
  },
};

export const INITIAL_STUDENTS: StudentUser[] = [
  {
    id: 'user-2024506117',
    regNo: '2024506117',
    name: 'Abinaya K',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    bio: 'Passionate about human-centered UI/UX design and frontend engineering. Enthusiastic about peer mentorship!',
    availability: 'Mon, Wed, Fri (4:00 PM - 6:00 PM)',
    rating: 4.9,
    totalReviews: 8,
    skillsToTeach: ['Figma UI Design', 'Frontend Development', 'React.js'],
    skillsToLearn: ['Python for AI', 'Data Structures & Algorithms', 'Docker & DevOps'],
    badges: [
      {
        id: 'b-1',
        studentId: 'user-2024506117',
        badgeKey: 'first_session',
        name: 'First Exchange',
        description: 'Completed your first peer learning session on campus.',
        icon: 'Sparkles',
        criteria: 'Complete at least 1 verified peer learning session as teacher or learner.',
        awardedAt: '2026-09-10T10:00:00Z',
      },
      {
        id: 'b-2',
        studentId: 'user-2024506117',
        badgeKey: 'top_mentor',
        name: 'Top Mentor',
        description: 'Earned stellar reviews by mentoring multiple campus peers.',
        icon: 'Award',
        criteria: 'Teach 2+ sessions with an average rating of 4.5 stars or above.',
        awardedAt: '2026-09-18T14:30:00Z',
      },
    ],
  },
  {
    id: 'user-2024506107',
    regNo: '2024506107',
    name: 'Keerthivasan U',
    department: 'Information Technology',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bio: 'Competitive programmer & AI enthusiast. Love breaking down complex graph algorithms and data structures.',
    availability: 'Tue, Thu, Sat (3:00 PM - 5:30 PM)',
    rating: 4.8,
    totalReviews: 12,
    skillsToTeach: ['Data Structures & Algorithms', 'Python for AI', 'System Design'],
    skillsToLearn: ['Figma UI Design', 'Public Speaking', 'Video Editing'],
    badges: [
      {
        id: 'b-3',
        studentId: 'user-2024506107',
        badgeKey: 'first_session',
        name: 'First Exchange',
        description: 'Completed your first peer learning session on campus.',
        icon: 'Sparkles',
        criteria: 'Complete at least 1 verified peer learning session as teacher or learner.',
        awardedAt: '2026-09-08T11:00:00Z',
      },
      {
        id: 'b-4',
        studentId: 'user-2024506107',
        badgeKey: 'multi_skill',
        name: 'Skill Pioneer',
        description: 'Versatile knowledge sharer offering 3 or more distinct skills.',
        icon: 'Zap',
        criteria: 'List and successfully teach across 3 or more distinct skill domains.',
        awardedAt: '2026-09-15T09:15:00Z',
      },
    ],
  },
  {
    id: 'user-2024506308',
    regNo: '2024506308',
    name: 'Mohanvel V',
    department: 'Computer Technology',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    bio: 'Media club lead. Teaching video editing, storytelling, color grading, and stage presentation confidence.',
    availability: 'Weekends (10:00 AM - 1:00 PM)',
    rating: 4.7,
    totalReviews: 6,
    skillsToTeach: ['Video Editing (Premiere Pro)', 'Public Speaking', 'Photography'],
    skillsToLearn: ['React.js', 'Node.js Backend'],
    badges: [
      {
        id: 'b-5',
        studentId: 'user-2024506308',
        badgeKey: 'first_session',
        name: 'First Exchange',
        description: 'Completed your first peer learning session on campus.',
        icon: 'Sparkles',
        criteria: 'Complete at least 1 verified peer learning session as teacher or learner.',
        awardedAt: '2026-09-12T16:00:00Z',
      },
    ],
  },
  {
    id: 'user-2024506129',
    regNo: '2024506129',
    name: 'Hasiba Aisha I',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    bio: 'Database optimizer and backend architecture enthusiast. Ready to help anyone struggling with SQL queries.',
    availability: 'Mon - Thu (5:00 PM - 7:00 PM)',
    rating: 4.9,
    totalReviews: 10,
    skillsToTeach: ['SQL & Database Design', 'MongoDB', 'Cloud Basics'],
    skillsToLearn: ['Flutter Mobile Dev', 'UI Animation'],
    badges: [
      {
        id: 'b-6',
        studentId: 'user-2024506129',
        badgeKey: 'top_mentor',
        name: 'Top Mentor',
        description: 'Earned stellar reviews by mentoring multiple campus peers.',
        icon: 'Award',
        criteria: 'Teach 2+ sessions with an average rating of 4.5 stars or above.',
        awardedAt: '2026-09-14T18:00:00Z',
      },
    ],
  },
  {
    id: 'user-2024506043',
    regNo: '2024506043',
    name: 'Kaviyun Ajees B',
    department: 'Information Technology',
    year: '2nd Year',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Mobile application developer with Flutter & Dart. Passionate about cross-platform app design.',
    availability: 'Wed, Fri (3:30 PM - 5:30 PM)',
    rating: 4.6,
    totalReviews: 4,
    skillsToTeach: ['Flutter Mobile Dev', 'Dart Programming'],
    skillsToLearn: ['System Design', 'Cybersecurity Basics'],
    badges: [],
  },
  {
    id: 'user-2024506007',
    regNo: '2024506007',
    name: 'Kaviya R',
    department: 'Electronics & Communication',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Embedded systems and IoT hobbyist. Exploring microcontrollers and Arduino projects.',
    availability: 'Mon, Tue (4:00 PM - 6:00 PM)',
    rating: 4.8,
    totalReviews: 5,
    skillsToTeach: ['Arduino & IoT', 'Embedded C'],
    skillsToLearn: ['Python for AI', 'Figma UI Design'],
    badges: [],
  },
  {
    id: 'user-2024506314',
    regNo: '2024506314',
    name: 'Vishwa M',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    bio: 'Linux enthusiast and DevOps explorer. Happy to teach bash scripting and Docker workflows.',
    availability: 'Thu, Fri (5:00 PM - 7:00 PM)',
    rating: 4.7,
    totalReviews: 7,
    skillsToTeach: ['Docker & DevOps', 'Linux & Bash Scripting'],
    skillsToLearn: ['Machine Learning', 'Public Speaking'],
    badges: [],
  },
  {
    id: 'user-2024506017',
    regNo: '2024506017',
    name: 'Nivetha G',
    department: 'Computer Science & Engineering',
    year: '2nd Year',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    bio: 'Web enthusiast specializing in Tailwind CSS and accessible web components.',
    availability: 'Tue, Thu (2:00 PM - 4:00 PM)',
    rating: 4.5,
    totalReviews: 3,
    skillsToTeach: ['Tailwind CSS', 'Web Accessibility'],
    skillsToLearn: ['SQL & Database Design', 'React.js'],
    badges: [],
  },
  {
    id: 'user-2024506312',
    regNo: '2024506312',
    name: 'Santhosh G',
    department: 'Information Technology',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    bio: 'Machine learning practitioner. Working on NLP and computer vision student projects.',
    availability: 'Weekdays (4:30 PM - 6:30 PM)',
    rating: 4.8,
    totalReviews: 9,
    skillsToTeach: ['Machine Learning', 'Python for AI'],
    skillsToLearn: ['Cloud Basics', 'Flutter Mobile Dev'],
    badges: [],
  },
  {
    id: 'user-2024506021',
    regNo: '2024506021',
    name: 'Suryarishi R',
    department: 'Computer Technology',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    bio: 'Cybersecurity explorer. Interested in network security, ethical hacking, and CTF challenges.',
    availability: 'Fri, Sat (3:00 PM - 6:00 PM)',
    rating: 4.6,
    totalReviews: 4,
    skillsToTeach: ['Cybersecurity Basics', 'Network Security'],
    skillsToLearn: ['Figma UI Design', 'System Design'],
    badges: [],
  },
];
