import { StudentUser } from '../types';

export const INITIAL_STUDENTS: StudentUser[] = [
  {
    id: 'user-2024506117',
    regNo: '2024506117',
    name: 'Abinaya K',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    totalReviews: 12,
    badges: ['UI Maestro', 'Top Contributor', 'Fast Responder'],
    skillsToTeach: ['Figma UI Design', 'Frontend Development', 'React.js'],
    skillsToLearn: ['Data Structures & Algorithms', 'Python for AI', 'Docker & DevOps'],
    bio: 'Passionate about human-centered UI/UX and web development. Excited to swap design skills for backend/DSA mentoring!',
    availability: 'Mon, Wed, Fri (4:00 PM - 6:00 PM)',
  },
  {
    id: 'user-2024506107',
    regNo: '2024506107',
    name: 'Keerthivasan U',
    department: 'Information Technology',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    totalReviews: 24,
    badges: ['DSA Ace', 'Python Master', 'Campus Mentor'],
    skillsToTeach: ['Data Structures & Algorithms', 'Python for AI', 'System Design'],
    skillsToLearn: ['Figma UI Design', 'Public Speaking', 'Video Editing'],
    bio: 'Competitive programmer & AI enthusiast. Enjoy teaching graph algorithms and building intelligent systems.',
    availability: 'Tue, Thu, Sat (3:00 PM - 5:30 PM)',
  },
  {
    id: 'user-2024506308',
    regNo: '2024506308',
    name: 'Mohanvel V',
    department: 'Computer Technology',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    rating: 4.7,
    totalReviews: 9,
    badges: ['Video Creator', 'Presentation Pro'],
    skillsToTeach: ['Video Editing (Premiere Pro)', 'Public Speaking', 'Photography'],
    skillsToLearn: ['React.js', 'Node.js Backend'],
    bio: 'Media club lead. Teaching camera techniques, storytelling, and stage confidence.',
    availability: 'Weekends (10:00 AM - 1:00 PM)',
  },
  {
    id: 'user-2024506129',
    regNo: '2024506129',
    name: 'Hasiba Aisha I',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    totalReviews: 18,
    badges: ['Database Wizard', 'Cloud Champion'],
    skillsToTeach: ['SQL & Database Design', 'MongoDB', 'Cloud Basics'],
    skillsToLearn: ['Flutter Mobile Dev', 'UI Animation'],
    bio: 'Backend enthusiast and database optimizer. Ready to help anyone struggling with complex queries!',
    availability: 'Mon - Thu (5:00 PM - 7:00 PM)',
  },
];
